### ISSUE TITLE
Review of grails mock basics guide

### ISSUE THREAD

**Issue by niravassar** [grails-guides/grails-mock-basics#3]
@sdelamo i have finished the guide to state where it can be reviewed. Please take a look and let me know edits and suggestions.

The last steps i will take for this guide for for me to repeat it end to end as a user, and also add some HTTP links within the content.

Thank you

**Comment by niravassar** [comment]
i have done the run through and added links. It is ready for review. thank you

**Comment by sdelamo** [comment]
I've reviewed and created a [pullrequest](https://github.com/grails-guides/grails-mock-basics/pull/4).
